import io
import csv
from datetime import datetime
from typing import List
from app.schemas.schemas import TransactionResponse, PnLResponse



def generate_pdf_statement_bytes(
    transactions: List[TransactionResponse],
    pnl: PnLResponse,
    period_label: str
) -> bytes:
    try:
        from fpdf import FPDF
    except ImportError:
        print("fpdf module not found. Please install fpdf or fpdf2.")
        return b""

    class PDFReport(FPDF):
        def header(self):
            self.set_font('Helvetica', 'B', 15)
            self.set_text_color(15, 23, 42)
            self.cell(0, 10, 'Financial Statement', ln=True, align='C')
            self.set_font('Helvetica', 'I', 10)
            self.set_text_color(16, 185, 129)
            self.cell(0, 10, 'Generated by Cyber Nuts AI Accounting', ln=True, align='C')
            self.ln(10)

        def footer(self):
            self.set_y(-15)
            self.set_font('Helvetica', 'I', 8)
            self.set_text_color(128, 128, 128)
            self.cell(0, 10, f'Page {self.page_no()}', 0, 0, 'C')

    pdf = PDFReport(orientation='P', unit='mm', format='A4')
    pdf.add_page()
    
    # Title & Metadata
    pdf.set_font('Helvetica', 'B', 12)
    pdf.set_text_color(69, 90, 100)
    pdf.cell(0, 8, f"Period: {period_label}", ln=True, align='R')
    pdf.cell(0, 8, f"Generated On: {datetime.now().strftime('%Y-%m-%d %H:%M')}", ln=True, align='R')
    pdf.ln(10)

    # 1. P&L Summary Section
    pdf.set_font('Helvetica', 'B', 14)
    pdf.set_text_color(15, 23, 42)
    pdf.cell(0, 10, 'Profit and Loss Summary', ln=True)
    pdf.ln(2)

    pdf.set_font('Helvetica', '', 10)
    pdf.set_text_color(33, 33, 33)
    
    pdf.cell(80, 8, "Total Income:", border=0)
    pdf.set_text_color(16, 185, 129) # Emerald
    pdf.cell(0, 8, f"PKR {pnl.total_income:,.2f}", border=0, ln=True, align='R')
    
    pdf.set_text_color(33, 33, 33)
    pdf.cell(80, 8, "Total Expenses:", border=0)
    pdf.set_text_color(229, 57, 53) # Red
    pdf.cell(0, 8, f"PKR {pnl.total_expenses:,.2f}", border=0, ln=True, align='R')
    
    pdf.set_font('Helvetica', 'B', 11)
    pdf.set_text_color(33, 33, 33)
    pdf.cell(80, 10, "NET PROFIT:", border=0)
    net_profit = pnl.total_income - pnl.total_expenses
    color = (16, 185, 129) if net_profit >= 0 else (229, 57, 53)
    pdf.set_text_color(*color)
    pdf.cell(0, 10, f"PKR {net_profit:,.2f}", border=0, ln=True, align='R')
    pdf.ln(10)

    # 2. Category Breakdowns
    pdf.set_font('Helvetica', 'B', 12)
    pdf.set_text_color(15, 23, 42)
    pdf.cell(0, 10, 'Category Breakdown (Income)', ln=True)
    pdf.set_font('Helvetica', '', 10)
    pdf.set_text_color(33, 33, 33)
    if pnl.income_breakdown:
        for item in pnl.income_breakdown:
            pdf.cell(80, 8, item.category)
            pdf.cell(0, 8, f"PKR {item.amount:,.2f}", ln=True, align='R')
    else:
        pdf.cell(0, 8, "No income recorded for this period.", ln=True)
    pdf.ln(5)

    pdf.set_font('Helvetica', 'B', 12)
    pdf.set_text_color(15, 23, 42)
    pdf.cell(0, 10, 'Category Breakdown (Expenses)', ln=True)
    pdf.set_font('Helvetica', '', 10)
    pdf.set_text_color(33, 33, 33)
    if pnl.expense_breakdown:
        for item in pnl.expense_breakdown:
            pdf.cell(80, 8, item.category)
            pdf.cell(0, 8, f"PKR {item.amount:,.2f}", ln=True, align='R')
    else:
        pdf.cell(0, 8, "No expenses recorded for this period.", ln=True)
    pdf.ln(10)

    # 3. Transaction Ledger
    pdf.set_font('Helvetica', 'B', 14)
    pdf.set_text_color(15, 23, 42)
    pdf.cell(0, 10, 'Detailed Transaction Ledger', ln=True)
    pdf.ln(2)

    # Table Header
    pdf.set_font('Helvetica', 'B', 9)
    pdf.set_fill_color(15, 23, 42)
    pdf.set_text_color(255, 255, 255)
    col_widths = [25, 20, 30, 35, 55, 25]
    headers = ["Date", "Type", "Category", "Account", "Description", "Amount"]
    for i, h in enumerate(headers):
        pdf.cell(col_widths[i], 8, h, border=1, fill=True, align='C')
    pdf.ln()

    # Table Body
    pdf.set_font('Helvetica', '', 8)
    pdf.set_text_color(33, 33, 33)
    for t in transactions:
        pdf.cell(col_widths[0], 8, t.date.strftime("%Y-%m-%d"), border=1, align='C')
        t_type = "Income" if t.type == "income" else "Expense"
        pdf.cell(col_widths[1], 8, t_type, border=1, align='C')
        cat = t.category.name if t.category else "N/A"
        pdf.cell(col_widths[2], 8, cat[:15], border=1, align='C')
        acc = t.account.name if t.account else "N/A"
        pdf.cell(col_widths[3], 8, acc[:20], border=1, align='C')
        desc = (t.description or "")[:30]
        pdf.cell(col_widths[4], 8, desc, border=1, align='L')
        pdf.cell(col_widths[5], 8, f"{t.amount:,.0f}", border=1, align='R')
        pdf.ln()

    return bytes(pdf.output())

def generate_csv_statement_string(
    transactions: List[TransactionResponse],
    pnl: PnLResponse,
    period_label: str
) -> str:
    output = io.StringIO()
    writer = csv.writer(output)

    writer.writerow(["FINANCIAL STATEMENT EXPORT"])
    writer.writerow(["Period:", period_label])
    writer.writerow(["Generated On:", datetime.now().strftime("%Y-%m-%d %H:%M")])
    writer.writerow([])
    
    writer.writerow(["PROFIT AND LOSS SUMMARY"])
    writer.writerow(["Total Income", f"{pnl.total_income:.2f}"])
    writer.writerow(["Total Expenses", f"{pnl.total_expenses:.2f}"])
    writer.writerow(["Net Profit", f"{pnl.net_profit:.2f}"])
    writer.writerow([])
    
    writer.writerow(["INCOME BREAKDOWN"])
    for item in (pnl.income_breakdown or []):
        writer.writerow([item.category, f"{item.amount:.2f}"])
    writer.writerow([])
    
    writer.writerow(["EXPENSE BREAKDOWN"])
    for item in (pnl.expense_breakdown or []):
        writer.writerow([item.category, f"{item.amount:.2f}"])
    writer.writerow([])

    writer.writerow(["TRANSACTION LEDGER"])
    writer.writerow(["ID", "Date", "Type", "Amount", "Account", "Category", "Description"])
    for t in transactions:
        writer.writerow([
            t.id,
            t.date.strftime("%Y-%m-%d"),
            t.type.upper(),
            f"{t.amount:.2f}",
            t.account.name if t.account else "N/A",
            t.category.name if t.category else "N/A",
            t.description or ""
        ])

    return output.getvalue()
